name: ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gcc
  - gxx
  - cmake
  - make
  - opencv
  - tensorflow
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8