#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:a100
#SBATCH --job-name=train_model
#SBATCH -o train_model.out

conda activate torch

cd ~/dev/pattern-analysis-2025/code

python fast_cifar10.py
